name: Build checker dispatcher image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SA_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate with Docker
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet
      - uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Build an image
        run: |
          pack build ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/app/checker-dispatcher:latest \
            --builder gcr.io/buildpacks/builder:v1 \
            --path ./services/checker-dispatcher
          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/app/checker-dispatcher:latest
